apiVersion: batch.my.domain/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: go-stuff
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  # TODO(user): Add fields here
